### ISSUE TITLE
Comment from a work-through

### ISSUE THREAD

**Issue by katilp** [awesome-workshop/intro-to-docker#3]
This looks really very good, I've learnt a lot!! I have only some minor remarks, but there's really nothing important in them. 

02-pulling-images
- I'm a good girl and I did the pulls beforehand as instructed in `Setup` : maybe add a mention of it before the first command instruction which seems to assume that the pulls were not yet done
- that's also valid just before `docker pull debian:buster`

03-running-containers
- not sure if necessary, but one could remind people to go back to the container screen under "Exiting and restarting containers" since the previous commands were on another terminal
- again for the sake of completeness, one could add after "For example, the exec equivalent to attaching in our case would look like:"  `docker start <CONTAINER ID>` although people will figure that out soon as I did ;-)

04-file-io
- as using <NAME> is much more practical than using <CONTAINER ID>, one could rather have the first cp command as 
`docker cp io_example.txt <NAME>:/home/docker/data/`
and similarly for the second.

05-dockerfiles
- "example" or similar missing in the sentence: "As a very simple ?? of extending the example image"?
- After "COPY": "copying a target file **on the from** a host file system into the Docker image file system" 

I'll continue below later on

**Comment by danikam** [comment]
Thank you so much @katilp for your careful work-through and awesome comments - all have been now been incorporated! This is super appreciated!! Moving to part II :)
