### ISSUE TITLE
Comments 10-containerized-analysis

### ISSUE THREAD

**Issue by katilp** [awesome-workshop/intro-to-docker#5]
- [x] maybe a friendly reminder to check `git remote -v` and `git remote set-url origin...` as we are changing from a repository from another when advising to "commit and push the new file to the fitting repo"?

- [x] I have added the image building stage as instructed to .gitlab-ci.yml from [the homework](https://awesome-workshop.github.io/continuous-integration-deployment-gitlab/15-homework/index.html) (or cheating from [here](https://gitlab.cern.ch/awesome-workshop/awesome-analysis-statistics-stage2/blob/master/.gitlab-ci.yml). The fitting part of it  contains: `xrdcp root://eosuser.cern.ch//eos/user/m/meehan/APBootCampFeb20/Histograms/histograms.root histograms.root
` which breaks the job in the container (/usr/bin/bash: line 95: xrdcp: command not found). Is that expected? I understand that I could read them from my own eos area, instead from that of Sam, but the problem here is that the command itself is not found and not the access to the area. The image is however built, and I can open it and it contains ` fit` directory as expected

- [x] It would be maybe useful to explain how to see on gitlab (web interface) which images I have in the gitlab-registry

**Comment by danikam** [comment]
Hi @katilp, thanks for all your thorough comments! I'm puzzled by the issue in your second bullet point - would you mind please sending a link to your gitlab repo so I can try to understand where the issue is coming from?

**Comment by katilp** [comment]
Hi @danikam , this is the error https://gitlab.cern.ch/kati/awesome-analysis-statistics/-/jobs/7206840
It is likely that I have messed up something but it is maybe not unlikely that the participants will do the same😉

**Comment by danikam** [comment]
Thanks for sharing! Ah, I see - the global image declaration strikes again!! I'll explain in a moment...

**Comment by katilp** [comment]
OK, got it already 😄

**Comment by danikam** [comment]
Nice! Ya, I think (especially since Giordon doesn't seem to be using it anyway), this global image declaration should probably be removed from these starter repos in favour of just specifying the image on a stage-by-stage basis. I'll make a merge request to both repos for this update. Many thanks @katilp for uncovering this inconsistency and source of confusion!!
